name: Latest Cyber Threat Feed

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-threats:
    name: Update README with latest threat intel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Pull RSS Feeds
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "THREAT_FEED"
          commit_message: "Updated Threat Feed"
          max_post_count: 5
          feed_list: "https://www.cisa.gov/cybersecurity-advisories/all.xml, https://feeds.feedburner.com/TheHackersNews"
